version: "3.9"

services:
  api:
    image: flobbe9/word_light_gateway
    container_name: ${API_NAME}
    ports: 
      - ${API_PORT}:${API_PORT}
    environment:
      # replace prod ip for local testing
      - HOST=localhost