server:
    port: ${API_PORT}
    error:
        include-message: always

spring:
    application:
        name: ${API_NAME}
    config:
        # include .env file
        import: optional:file:.env[.properties]