name: word_light_gateway dev

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      - run: gradle clean build
