name: word_light_gateway main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      - run: gradle clean build
  
  push_to_Dockerhub:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/word_light_gateway:latest

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: push_to_Dockerhub

    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with: 
          host: word-light.de
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          # pull new image, remove left overs from old image, start microservice
          script: |
            docker-compose pull gateway
            yes | docker rm $(docker container ls --all --filter=ancestor=$(docker images -f "dangling=true" -q) --format "{{.ID}}") --force
            yes | docker image rm $(docker images -f "dangling=true" -q)
            docker-compose up -d